### PR TITLE
BatchThumbnailProcess and CreateThumbnailProcess are deprecated

### PR DESCRIPTION
**Pull request by synox**
As part of CQ-4299985, marked BatchThumbnailProcess and CreateThumbnailProcess as deprecated. 

## Related Issue

CQ-4299985 

## Motivation and Context

Detect workflows which are not compatible with AEM as a Cloud Service

## How Has This Been Tested?

(not tested)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by synox** [comment]
@dichaudhary please review. I did not try to run it yet.

**Comment by dichaudhary** [comment]
Hi @synox, Thanks for the PR, here the list `NUI_MIGRATED` contains the processes for which we are creating the processing profiles supported on AEMaaCS (ex: https://github.com/adobe/aem-cloud-migration/blob/7cbcd3e285dca2f71fd10ae975734fc11ff6f71b/src/main/java/com/adobe/skyline/migration/transformer/processingprofile/mappers/ThumbnailProcessMapper.java), Ideally the processes should go to `UNSUPPORTED` if they are incompatible on CS. A short description of the intention for each of these types is [here](https://github.com/adobe/aem-cloud-migration/blob/master/src/main/java/com/adobe/skyline/migration/model/WorkflowStepSupportStatus.java) 
Thanks,

cc: @ireasor

**Review by ireasor — CHANGES_REQUESTED** [review]
I agree with @dichaudhary.  NUI_MIGRATED signifies that we have taken actions to generate processing profiles for the workflow steps, which in this case we have not.  As a result, these should be listed under UNSUPPORTED.  We could potentially add logic to the migration tool to read configurations for these processes and use them to generate processing profiles, at which point they could be listed under NUI_MIGRATED.

**Comment by synox** [comment]
Thanks for your feedback. 
I made the changes and run the tests.

**Review by ireasor — APPROVED** [review]

**Comment by ireasor** [comment]
LGTM!

**Pull request merged**
